version: '3.7'

services:
  go:
    build:
      dockerfile: Dockerfile.dev
      context: .
      target: build
    volumes:
      - ./:/go/app
    command: >
      air
      sql-migrate up
    ports:
      - 8080:8080
      - 2345:2345
      - 6060:6060
    security_opt:
      - apparmor:unconfined
    tty: true
    cap_add:
      - SYS_PTRACE
    stdin_open: true