FROM golang:1.14-alpine3.11 as build

LABEL maintainer="https://github.com/yosuke0517"

WORKDIR /go/app

COPY . .

ENV GO111MODULE=off
ENV CGO_ENABLED=0

RUN set -eux && \
  apk update && \
  apk add --no-cache git curl gcc alpine-sdk && \
  go get -u github.com/cosmtrek/air && \
  go get -u github.com/labstack/echo/... && \
  go get -u github.com/go-delve/delve/cmd/dlv && \
  go get golang.org/x/tools/cmd/godoc && \
  go get -v github.com/rubenv/sql-migrate/... && \
  go build -o /go/bin/dlv github.com/go-delve/delve/cmd/dlv

ENV GO111MODULE on

RUN set -eux && \
  go build -o system-trade-api ./main.go

FROM alpine:3.11

WORKDIR /app

COPY --from=build /go/app/system-trade-api .

RUN set -x && \
  addgroup go && \
  adduser -D -G go go && \
  chown -R go:go /app/system-trade-api

#CMD ["./system-trade-api"]
CMD ["/startup.sh"]