version: '3.7'

services:
  go:
    build:
      dockerfile: Dockerfile.dev
      context: .
      target: build
    volumes:
      - ./:/go/app
    command: >
      air
      sql-migrate up
    ports:
      - 8080:8080
      - 2345:2345
      - 6060:6060
    security_opt:
      - apparmor:unconfined
    tty: true
    cap_add:
      - SYS_PTRACE
    stdin_open: true
  db:
    build:
      # dockerfileの名前だけ指定する
      dockerfile: Dockerfile
      # contextで場所を指定する
      context: ./mysql
    env_file:
      - .env
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Tokyo
    ports:
      - 3305:3305
    expose:
      - 3305
    volumes:
      - ./dbdata:/var/lib/mysql
volumes:
  dbdata: